-- Example of how to get started
-- CREATE DATABASE database_name;
-- CREATE USER user_name
-- WITH
--   encrypted password 'password in single quotes';
-- GRANT ALL privileges ON database database_name TO user_name;
-- -- \connect database_name
-- CREATE SCHEMA schema_name probably the same as the database_name AUTHORIZATION user_name;
