import './globals.scss';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUser } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Event Network',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};
export default async function RootLayout({ children }: Props) {
  const sessionCookie = cookies().get('sessionToken');

  const user = sessionCookie && (await getUser(sessionCookie.value));

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <nav>
            <div>
              <Link href="/">Home</Link>
              <Link href="/events">Upcoming Events</Link>
              <div>
                {user ? (
                  <>
                    <Link href={`/profile/${user.username}`}>
                      {user.username}
                    </Link>
                    <LogoutButton />
                  </>
                ) : (
                  <>
                    <Link href="/register">Register</Link>
                    <Link href="/login">Login</Link>
                  </>
                )}
              </div>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
